# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e051eb162bdd6868f83b7b6ebc5ab314e22ca60a31c14a2f34d1416b6551be569a4dca3fd4da8836667ff99dbc1b07a57ddb840706e2a8d7cdb75a5a5fcdac4

test:
  secret_key_base: cd0597288f30f9d963f6f9b6b07dde757c36ec36bb556ebcb3c6d24e843da62c48a3c8df4fcaa6aa73fdf55aaee52662b63c113e25bc846134fabc3e79ebcd36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
